version: "3"
services:
    db:
       image: mysql:latest
       container_name: mysql_container
       volumes:
            - mysql_volume:/var/lib/mysql
       networks:
            - my_network
       environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=hr
       
    employee-app-backend:
       image: amitfegade121/spring-boot-employee-app:1.0
       container_name: employee-app
       networks:
            - my_network
       environment:
            - RDS_HOSTNAME=mysql_container
       depends_on:
            - db
       ports:
            - "8080:8080"

    employee-app-frontend:
       image: amitfegade121/employee-app-client
       container_name: employee-app-client
       networks:
            - my_network
       depends_on:
            - employee-app-backend
       ports:
            - "80:80"         

volumes:
    mysql_volume:

networks:
    my_network:


